import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, existsSync, mkdirSync } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Local vault path — used for dev builds. Set to your vault's plugin dir.
// On CI (GitHub Actions), this path won't exist, so we output to ./main.js instead.
const vaultPluginDir =
	"/Users/jisirivorawo/Library/Mobile Documents/iCloud~md~obsidian/Documents/Notes/.obsidian/plugins/handwriting-to-text";

const useVaultDir = existsSync(vaultPluginDir);
const outfile = useVaultDir ? `${vaultPluginDir}/main.js` : "main.js";

if (useVaultDir) {
	copyFileSync("manifest.json", `${vaultPluginDir}/manifest.json`);
	copyFileSync("styles.css", `${vaultPluginDir}/styles.css`);
}

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
